/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Comment: () => import('#controllers/comment_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Post: () => import('#controllers/post_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
